import { select } from "motion/react-client";

export const Categories = [
  {
    id: "1",
    name: "Product & Strategy",
    subCategories: [
      "Product Manager",
      "Project Manager",
      "Business Analyst",
      "Technical Program Manager",
      "Product Designer",
      "Scrum Master",
      "Chief of Staff",
    ],
    showSubCategories: false,
  },
  {
    id: "2",
    name: "Engineering & Development",
    subCategories: [
      "Frontend Developer",
      "Backend Developer",
      "Full Stack Developer",
      "Mobile App Developer",
      "DevOps Engineer",
      "QA Engineer",
      "Site Reliability Engineer",
      "Software Engineer",
      "Security Engineer",
      "Data Engineer",
      "Game Developer",
      "Embedded Systems Engineer",
      "AR/VR Developer",
    ],
    showSubCategories: false,
  },
  {
    id: "3",
    name: "Web3 & Blockchain",
    subCategories: [
      "Frontend Developer Web3",
      "Backend Developer Web3",
      "Blockchain Developer",
      "Smart Contract Developer",
      "Rust Developer",
      "Protocol Engineer",
      "DApp Developer",
      "Wallet Integration Engineer",
      "ZK-SNARK Developer",
      "Smart Contract Auditor",
      "Tokenomics Expert",
      "DAO Coordinator",
      "Web3 Security Analyst",
    ],
    showSubCategories: false,
  },
  {
    id: "4",
    name: "Data & AI",
    subCategories: [
      "Data Scientist",
      "Data Analyst",
      "Machine Learning Engineer",
      "AI/ML Researcher",
      "NLP Engineer",
      "Computer Vision Engineer",
    ],
    showSubCategories: false,
  },
  {
    id: "5",
    name: "Design & Creative",
    subCategories: [
      "UI Designer",
      "UX Researcher",
      "Graphic Designer",
      "Brand Designer",
      "Motion Designer",
      "Illustrator",
      "Creative Director",
    ],
    showSubCategories: false,
  },
  {
    id: "6",
    name: "Marketing & Community",
    subCategories: [
      "Marketing Manager",
      "Performance Marketer",
      "Growth Hacker",
      "Community Manager",
      "Social Media Manager",
      "Content Writer",
      "SEO Specialist",
      "Copywriter",
      "Email Marketing Specialist",
      "PR Manager",
      "Influencer Marketing Specialist",
    ],
    showSubCategories: false,
  },
  {
    id: "7",
    name: "Operations & People",
    subCategories: [
      "HR / Talent Acquisition",
      "People Operations",
      "Office Manager",
      "Operations Manager",
      "Customer Support",
      "Tech Support",
      "Legal Counsel",
      "Compliance Officer",
      "Finance Manager",
      "Accountant",
    ],
    showSubCategories: false,
  },
  {
    id: "8",
    name: "Sales & BizDev",
    subCategories: [
      "Business Development Manager",
      "Sales Executive",
      "Account Manager",
      "Partnerships Manager",
      "Customer Success Manager",
      "Revenue Operations",
    ],
    showSubCategories: false,
  },
  {
    id: "9",
    name: "Specialized / Niche",
    subCategories: [
      "Developer Advocate",
      "Technical Writer",
      "Release Manager",
      "Accessibility Specialist",
      "Localization Manager",
      "Cloud Architect",
      "Platform Engineer",
      "White Hat Hacker",
      "Threat Analyst",
      "Token Listing Specialist",
    ],
    showSubCategories: false,
  },
];
