export const Categories = [
  {
    id: "1",
    name: "Product & Strategy",
    subCategories: [
      "product manager",
      "project manager",
      "business analyst",
      "technical program manager",
      "product designer",
      "scrum master",
    ],
    showSubCategories: false,
  },
  {
    id: "2",
    name: "Engineering & Development",
    subCategories: [
      "frontend developer",
      "backend developer",
      "full stack developer",
      "mobile app developer",
      "devops engineer",
      "qa engineer",
      "site reliability engineer",
      "software engineer",
      "security engineer",
      "data engineer",
      "game developer",
    ],
    showSubCategories: false,
  },
  {
    id: "3",
    name: "Web3 & Blockchain",
    subCategories: [
      "blockchain developer",
      "smart contract developer",
      "rust developer",
      "protocol engineer",
      "dapp developer",
      "wallet integration engineer",
      "zk-snark developer",
      "smart contract auditor",
      "tokenomics expert",
      "dao coordinator",
    ],
    showSubCategories: false,
  },
  {
    id: "4",
    name: "Data & AI",
    subCategories: [
      "data scientist",
      "data analyst",
      "machine learning engineer",
      "ai/ml researcher",
      "nlp engineer",
      "computer vision engineer",
    ],
    showSubCategories: false,
  },
  {
    id: "5",
    name: "Design & Creative",
    subCategories: [
      "ui designer",
      "ux researcher",
      "graphic designer",
      "brand designer",
      "motion designer",
      "illustrator",
      "creative director",
    ],
    showSubCategories: false,
  },
  {
    id: "6",
    name: "Marketing & Community",
    subCategories: [
      "marketing manager",
      "performance marketer",
      "growth hacker",
      "community manager",
      "social media manager",
      "content writer",
      "seo specialist",
      "copywriter",
      "email marketing specialist",
      "pr manager",
      "influencer marketing specialist",
    ],
    showSubCategories: false,
  },
  {
    id: "7",
    name: "Operations & People",
    subCategories: [
      "hr / talent acquisition",
      "people operations",
      "office manager",
      "operations manager",
      "customer support",
      "tech support",
      "legal counsel",
      "compliance officer",
      "finance manager",
      "accountant",
    ],
    showSubCategories: false,
  },
  {
    id: "8",
    name: "Sales & BizDev",
    subCategories: [
      "business development manager",
      "sales executive",
      "account manager",
      "partnerships manager",
      "customer success manager",
      "revenue operations",
    ],
    showSubCategories: false,
  },
  {
    id: "9",
    name: "Specialized / Niche",
    subCategories: [
      "developer advocate",
      "technical writer",
      "release manager",
      "accessibility specialist",
      "localization manager",
      "cloud architect",
      "platform engineer",
      "white hat hacker",
      "threat analyst",
      "token listing specialist",
    ],
    showSubCategories: false,
  },
];
